apiVersion: v1
kind: Pod
metadata:
  name: demo-target-pss
  namespace: demo-sec
spec:
  containers:
  - name: app
    image: ali20052025/secure-app:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
