driver:
  kind: modern_ebpf

tty: true

falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/custom-rules.yaml
  http_output:
    enabled: true
    url: "http://falco-falcosidekick.falco.svc.cluster.local:2801"
    insecure: true

falcosidekick:
  enabled: true
  webui:
    enabled: true
    user: "admin:admin"
    service:
      type: NodePort
      nodePort: 30282
  config:
    webhook:
      address: "http://falco-response.demo-sec.svc.cluster.local:5000/falco"
      checkcert: false

mounts:
  volumes:
    - name: custom-rules
      configMap:
        name: falco-custom-rules
  volumeMounts:
    - name: custom-rules
      mountPath: /etc/falco/custom-rules.yaml
      subPath: custom-rules.yaml

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 500m
